#!/usr/bin/env python3
"""# SAMBA - BIDS App Entry Point

Pipeline generated from code repository

Generated by Paper2BIDS
Repository: https://github.com/andersonion/SAMBA
Usage:
    ./run.py /path/to/bids /path/to/output participant [options]
"""

from pathlib import Path

from snakebids import bidsapp, plugins


def get_app():
    """Create and configure the BIDS app."""
    return bidsapp.app(
        [
            plugins.SnakemakeBidsApp(Path(__file__).resolve().parent),
        ]
    )


app = get_app()


if __name__ == "__main__":
    app.run()